version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --region us-west-2 ecr get-login-password | docker login --username AWS --password-stdin 142496269814.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Building the climate-health R API Docker image...
      - docker build -t ons-climate-health/climatehealth .
  post_build:
    commands:
      - echo Tagging and pushing the data-explorer Docker image...
      - VERSION=$(grep 'Version:' ./climatehealth.Rproj | cut -d ' ' -f 2)
      - docker tag ons-climate-health/climatehealth:latest 142496269814.dkr.ecr.us-west-2.amazonaws.com/ons-climate-health/climatehealth:$VERSION
      - docker push 142496269814.dkr.ecr.us-west-2.amazonaws.com/ons-climate-health/climatehealth:$VERSION
      - echo Build completed on `date`