default:
  # Input data
  input_csv_path: 'tests/testthat/testdata/regEngWales.csv'

  #Output folder path
  output_folder_path: 'output/'

  # Specification of the exposure function
  varfun: 'bs'
  vardegree:  2
  varper: !expr c(10, 75, 90)

  # Specification of the lag function
  lag: 21
  lagnk: 3

  # Degree of freedom for seasonality
  dfseas: 8
