apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: unified-route
  namespace: ons-data-explorer
spec:
  http:
    - name: r-api-route
      match:
        hosts:
          - climate-health.dev.officialstatistics.org
        paths:
          - /r/*
      backends:
        - serviceName: r-api
          servicePort: 80
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/r/(.*)"
              - "/$1"
        - enable: true
          name: basic-auth
    - name: data-explorer-root
      match:
        hosts:
          - climate-health.dev.officialstatistics.org
        paths:
          - /*
      backends:
        - serviceName: data-explorer-service
          servicePort: 80
      plugins:
        - enable: true
          name: basic-auth
