name: R CMD Check

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  check-macos:
    runs-on: macos-latest
    name: Run R CMD Check on MacOS
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.1"

      - name: Install dependencies
        run: |
          Rscript -e 'options(repos = c(CRAN = "https://packagemanager.posit.co/cran/latest"))'
          Rscript -e 'install.packages(c("devtools", "roxygen2", "remotes", "patrick", "pak"))'
          Rscript -e 'pak::pkg_install(devtools::dev_package_deps()$package)'
          
      - name: Check Package
        run: |
          R CMD check .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
